#include "hwinterface.h"

void HwInterface_Init(void)
{
    UART_RX_TRIS = 1;
    UART_TX_TRIS = 0;
    MAIN_MOTOR_TRIS = 0;
    STEPDRV_0_DIR_TRIS = 0;
    STEPDRV_0_STEP_TRIS = 0;
    STEPDRV_0_ENABLE_TRIS = 0;
    STEPDRV_0_MS1_TRIS = 0;
    STEPDRV_0_MS2_TRIS = 0;
    STEPDRV_1_DIR_TRIS = 0;
    STEPDRV_1_STEP_TRIS = 0;
    STEPDRV_1_ENABLE_TRIS = 0;
    STEPDRV_1_MS1_TRIS = 0;
    STEPDRV_1_MS2_TRIS = 0;
    STEPDRV_2_DIR_TRIS = 0;
    STEPDRV_2_STEP_TRIS = 0;
    STEPDRV_2_ENABLE_TRIS = 0;
    STEPDRV_2_MS1_TRIS = 0;
    STEPDRV_2_MS2_TRIS = 0;
    LIMIT_SWITCH_BOTTOM_TRIS = 1;
    LIMIT_SWITCH_UP_TRIS = 1;
    
    MAIN_MOTOR_LAT = 0;
    
    STEPDRV_0_DIR_LAT = 0;
    STEPDRV_0_STEP_LAT = 0;
    STEPDRV_0_ENABLE_LAT = 0;
    STEPDRV_0_MS1_LAT = 0;
    STEPDRV_0_MS2_LAT = 0;
    STEPDRV_1_DIR_LAT = 0;
    STEPDRV_1_STEP_LAT = 0;
    STEPDRV_1_ENABLE_LAT = 0;
    STEPDRV_1_MS1_LAT = 0;
    STEPDRV_1_MS2_LAT = 0;
    STEPDRV_2_DIR_LAT = 0;
    STEPDRV_2_STEP_LAT = 0;
    STEPDRV_2_ENABLE_LAT = 0;
    STEPDRV_2_MS1_LAT = 0;
    STEPDRV_2_MS2_LAT = 0;
}
